# Use custom symbols and colors
format = """$character"""

# Move the rest of the indicators (git, package versions, etc.) to the right or disable them
# For a truly minimal setup, we only show the directory and the prompt character

[directory]
style = "blue bold"
truncation_length = 3
truncation_symbol = "…/"

[character]
#success_symbol = "[>](bold purple)"
# OR use a Hex code for a specific shade
 success_symbol = "[>](bold #BD93F9)" 
error_symbol = "[>](bold red)"
vicmd_symbol = "[<](bold green)"

# Disable modules that add clutter if you want it strictly minimal
[git_branch]
disabled = true

[package]
disabled = true