wallpaper {
    monitor = HDMI-A-3
    path = /home/michael/Bilder/AstronautEdited.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/michael/Bilder/AstronautEdited.png
    fit_mode = cover
}